site_name: Community operators
repo_name: community-operators
repo_url: https://github.com/operator-framework/community-operators
nav:
    - 'Home': index.md
    - 'Operator deployment':
      - 'Contribution via PR' : contributing.md
    - 'Operator testing' :
      - 'Using test suite' : using-current-test-suite.md
      - 'Manually': testing-operators.md
    - 'Operator versioning' : operator-versioning.md
theme:
  name: material
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate

hide:
  - navigation # Hide navigation
  - toc        # Hide table of contents

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.tabbed
  - toc:
      toc_depth: 2